baseURL = "https://emptyarea.com/"
languageCode = "en-us"
title = "emptyarea"
theme = "tailwind"
copyright = "Copyright © 2021 Powered by ❤ by "
assetDir = "static/img"
googleAnalytics = "G-P76JH01PZZ"

# menu
[[menu.main]]
URL = "/"
name = "Home"
weight = 1

[[menu.main]]
URL = "/work/"
name = "Work"
weight = 2

[[menu.main]]
URL = "/about/"
name = "About"
weight = 3

[[menu.main]]
URL = "/contact/"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = "img/logo-emptyarea.svg"
logo_light = "img/logo-light.svg"
# contact info
email = "taoguangc@gmail.com"
address = "125/A, CA Commercial Area, California, USA"
# meta description
author = "Jeffrey Qian"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright

imageWidths = [1500, 900, 600]

[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "static/img"
target = "assets/img"