[build]
  command = "hugo"
  context = "production"
  publish = "public"

[context.production.environment]
  NODE_VERSION = "16.13.1"
  HUGO_VERSION = "0.91.2"
  HUGO_ENV = "production"

[[headers]]
  for = "/*"

[headers.values]
  # Content-Security-Policy = "default-src 'none'; img-src 'self'; media-src 'self'; font-src https://fonts.gstatic.com https://fonts.googleapis.com; object-src 'none'; script-src 'self' https://www.google-analytics.com; style-src 'self'; frame-ancestors 'none'"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=15768000"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "1; mode=block"