[build]
  command = "hugo"
  context = "production"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.88.1"
  HUGO_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'https:'; font-src 'self' https://fonts.googleapis.com; object-src 'none'; script-src 'self' https://www.google-analytics.com https://cdn.jsdelivr.net style-src 'self' https://cdn.jsdelivr.net https://fonts.googleapis.com; base-uri https://emptyarea.com; frame-ancestors 'none'"
    Referrer-Policy = "strict-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"