[build]
  command = "hugo"
  context = "production"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.88.1"
  HUGO_ENV = "production"

[[headers]]
  for = "/*"

[headers.values]
  Content-Security-Policy = "default-src 'none'; img-src 'self'; media-src 'self'; font-src 'self' https://fonts.googleapis.com; object-src 'none'; script-src 'self' https://www.google-analytics.com https://cdn.jsdelivr.net; style-src 'none'; base-uri 'none'; frame-ancestors 'none'"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=15768000"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "1; mode=block"