backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'content/uploads'
public_folder: '/uploads'
collections:
  - name: 'work'
    label: 'Work'
    folder: 'content/work'
    create: true
    media_folder: '../uploads/work'
    public_folder: '/uploads/work'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - name: 'images'
        label: 'Images'
        widget: 'object'
        fields: 
          - { label: 'Image', name: 'image', widget: 'image' }

      - name: 'videos'
        label: 'Videos'
        widget: list
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'URL', name: 'URL', widget: 'string' }
      - { label: 'Test', name: 'test', widget: 'string' }
      - { label: 'Client', name: 'client', widget: 'string' }
      - { label: 'Project URL', name: 'project_url', widget: 'string', required: false }
      - { label: 'Categories', name: 'categories', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/_index.md'
        label: 'Home Page'
        name: 'home'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Images', name: 'images', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'content/about/_index.md'
        label: 'About Page'
        name: 'about'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Avatar', name: 'avatar', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'content/work/_index.md'
        label: 'Work Page'
        name: 'work'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }